# Generated by Django 2.0.1 on 2018-01-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ManyToManyField(to='demoapp.Person'),
        ),
    ]
